// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Puroguramu.Infrastructures.DbContexts;

#nullable disable

namespace Puroguramu.Infrastructures.Migrations.SqlServerMigrations
{
    [DbContext(typeof(ProdPuroguramuDbContext))]
    [Migration("20240425122447_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Puroguramu.Domains.Models.Difficulty", b =>
                {
                    b.Property<int>("IdDifficulte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDifficulte"), 1L, 1);

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdDifficulte");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            IdDifficulte = 1,
                            Libelle = "Facile"
                        },
                        new
                        {
                            IdDifficulte = 2,
                            Libelle = "Moyen"
                        },
                        new
                        {
                            IdDifficulte = 3,
                            Libelle = "Difficile"
                        });
                });

            modelBuilder.Entity("Puroguramu.Domains.Models.Exercise", b =>
                {
                    b.Property<int>("IDExercice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDExercice"), 1L, 1);

                    b.Property<string>("Enonce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDDifficulte")
                        .HasColumnType("int");

                    b.Property<int>("IDLecon")
                        .HasColumnType("int");

                    b.Property<int>("IDStatut")
                        .HasColumnType("int");

                    b.Property<string>("Modele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IDExercice");

                    b.HasIndex("IDDifficulte");

                    b.HasIndex("IDLecon");

                    b.HasIndex("IDStatut");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            IDExercice = 1,
                            Enonce = "Ceci est l'exercie qui a été donné en exemple dans le projet de base.",
                            IDDifficulte = 3,
                            IDLecon = 1,
                            IDStatut = 2,
                            Modele = "// code-insertion-point\n\npublic class Test \n{\n    public static TestResult Ensure(float b, int exponent, float expected) \n    {\n      TestStatus status = TestStatus.Passed;\n      float actual = float.NaN;\n      try \n      {\n         actual = Exercice.Power(b, exponent);\n         if(Math.Abs(actual - expected) > 0.00001f) \n         {\n             status = TestStatus.Failed;\n         }\n      } \n      catch(Exception ex) \n      {\n         status = TestStatus.Inconclusive;\n      }\n\n      return new TestResult(\n        string.Format(\"\"Power of {0} by {1} should be {2}\"\", b, exponent, expected),\n        status,\n        status == TestStatus.Passed ? string.Empty : string.Format(\"\"Expected {0}. Got {1}.\"\", expected, actual)\n      );  \n    }\n}\n\nreturn new TestResult[] {\n  Test.Ensure(2, 4, 16.0f),\n  Test.Ensure(2, -4, 1.0f/16.0f)\n};",
                            Position = 1,
                            Solution = "Aucune solution pour celui-ci, c'est l'exercice qui a été donné en exemple dans le projet de base.",
                            Titre = "Exercice d'exemple de base"
                        },
                        new
                        {
                            IDExercice = 2,
                            Enonce = "Écrivez une méthode statique Power dans la classe Exercice qui prend en entrée un nombre flottant baseNumber et un entier exponent et retourne baseNumber élevé à la puissance exponent. Vous devez gérer les cas où l'exposant est négatif ou zéro.",
                            IDDifficulte = 1,
                            IDLecon = 1,
                            IDStatut = 2,
                            Modele = "// code-insertion-point\n\npublic class Test \n{\n    public static TestResult Ensure(float b, int exponent, float expected) \n    {\n        TestStatus status = TestStatus.Passed;\n        float actual = float.NaN;\n        try \n        {\n            actual = Exercice.Power(b, exponent);\n            if(Math.Abs(actual - expected) > 0.00001f) \n            {\n                status = TestStatus.Failed;\n            }\n        } \n        catch(Exception ex) \n        {\n            status = TestStatus.Inconclusive;\n        }\n\n        return new TestResult(\n            string.Format(\"Power of {0} by {1} should be {2}\", b, exponent, expected),\n            status,\n            status == TestStatus.Passed ? string.Empty : string.Format(\"Expected {0}. Got {1}.\", expected, actual)\n        );  \n    }\n}\n\nreturn new TestResult[] {\n    Test.Ensure(2, 4, 16.0f),\n    Test.Ensure(2, -4, 1.0f/16.0f),\n    Test.Ensure(10, 0, 1.0f),\n    Test.Ensure(2, 1, 2.0f),\n    Test.Ensure(3, 3, 27.0f)\n};\n",
                            Position = 2,
                            Solution = "public class Exercice\n{\n    public static float Power(float baseNumber, int exponent)\n    {\n        if (exponent == 0) return 1.0f; // Cas de base pour exponent = 0\n        float result = 1.0f;\n        int absExponent = Math.Abs(exponent);\n        for (int i = 0; i < absExponent; i++)\n        {\n            result *= baseNumber;\n        }\n        return exponent > 0 ? result : 1.0f / result;\n    }\n}\n",
                            Titre = "Puissance d'un nombre"
                        },
                        new
                        {
                            IDExercice = 3,
                            Enonce = "Implémentez une méthode ReverseString dans la classe Exercice qui prend une chaîne de caractères en entrée et retourne cette chaîne inversée.",
                            IDDifficulte = 2,
                            IDLecon = 1,
                            IDStatut = 2,
                            Modele = "// code-insertion-point\n\npublic class Test \n{\n    public static TestResult Ensure(string input, string expected) \n    {\n        TestStatus status = TestStatus.Passed;\n        string actual = string.Empty;\n        try \n        {\n            actual = Exercice.ReverseString(input);\n            if(actual != expected) \n            {\n                status = TestStatus.Failed;\n            }\n        } \n        catch(Exception ex) \n        {\n            status = TestStatus.Inconclusive;\n        }\n\n        return new TestResult(\n            string.Format(\"Reverse of '{0}' should be '{1}'\", input, expected),\n            status,\n            status == TestStatus.Passed ? string.Empty : string.Format(\"Expected '{0}'. Got '{1}'.\", expected, actual)\n        );  \n    }\n}\n\nreturn new TestResult[] {\n    Test.Ensure(\"hello\", \"olleh\"),\n    Test.Ensure(\"world\", \"dlrow\"),\n    Test.Ensure(\"\", \"\"),\n    Test.Ensure(\"a\", \"a\")\n};\n",
                            Position = 3,
                            Solution = "public class Exercice\n{\n    public static string ReverseString(string input)\n    {\n        char[] charArray = input.ToCharArray();\n        Array.Reverse(charArray);\n        return new string(charArray);\n    }\n}\n",
                            Titre = "Inversion d'une chaîne"
                        },
                        new
                        {
                            IDExercice = 4,
                            Enonce = "Créez une méthode CountVowels qui reçoit une chaîne et retourne le nombre de voyelles (a, e, i, o, u, y) dans cette chaîne. Considerer les voyelles en majuscules également.",
                            IDDifficulte = 3,
                            IDLecon = 1,
                            IDStatut = 2,
                            Modele = "// code-insertion-point\n\npublic class Test \n{\n    public static TestResult Ensure(string input, int expected) \n    {\n        TestStatus status = TestStatus.Passed;\n        int actual = 0;\n        try \n        {\n            actual = Exercice.CountVowels(input);\n            if(actual != expected) \n            {\n                status = TestStatus.Failed;\n            }\n        } \n        catch(Exception ex) \n        {\n            status = TestStatus.Inconclusive;\n        }\n\n        return new TestResult(\n            string.Format(\"Number of vowels in '{0}' should be {1}\", input, expected),\n            status,\n            status == TestStatus.Passed ? string.Empty : string.Format(\"Expected {0}. Got {1}.\", expected, actual)\n        );  \n    }\n}\n\nreturn new TestResult[] {\n    Test.Ensure(\"hello\", 2),\n    Test.Ensure(\"world\", 1),\n    Test.Ensure(\"aeiouy\", 6),\n    Test.Ensure(\"bcdfgh\", 0),\n    Test.Ensure(\"YELLOWS\", 1)\n};\n",
                            Position = 4,
                            Solution = "public class Exercice\n{\n    public static int CountVowels(string input)\n    {\n        int count = 0;\n        string vowels = \"aeiouyAEIOUY\";\n        foreach (char c in input)\n        {\n            if (vowels.Contains(c))\n            {\n                count++;\n            }\n        }\n        return count;\n    }\n}\n",
                            Titre = "Compteur de voyelles"
                        },
                        new
                        {
                            IDExercice = 5,
                            Enonce = "Implémentez une méthode FindMax qui prend un tableau d'entiers en entrée et retourne l'élément le plus grand du tableau.",
                            IDDifficulte = 1,
                            IDLecon = 2,
                            IDStatut = 2,
                            Modele = "// code-insertion-point\n\npublic class Test \n{\n    public static TestResult Ensure(int[] numbers, int expected) \n    {\n        TestStatus status = TestStatus.Passed;\n        int actual = int.MinValue;\n        try \n        {\n            actual = Exercice.FindMax(numbers);\n            if(actual != expected) \n            {\n                status = TestStatus.Failed;\n            }\n        } \n        catch(Exception ex) \n        {\n            status = TestStatus.Inconclusive;\n        }\n\n        return new TestResult(\n            string.Format(\"The maximum value in the array should be {0}\", expected),\n            status,\n            status == TestStatus.Passed ? string.Empty : string.Format(\"Expected {0}. Got {1}.\", expected, actual)\n        );  \n    }\n}\n\nreturn new TestResult[] {\n    Test.Ensure(new int[]{ 1, 2, 3, 4, 5 }, 5),\n    Test.Ensure(new int[]{ 5, 4, 3, 2, 1 }, 5),\n    Test.Ensure(new int[]{ -10, 0, 10, 20 }, 20),\n    Test.Ensure(new int[]{ }, int.MinValue) // Cas d'un tableau vide\n};\n",
                            Position = 1,
                            Solution = "public class Exercice\n{\n    public static int FindMax(int[] numbers)\n    {\n        if (numbers.Length == 0)\n            return int.MinValue;\n        \n        int max = numbers[0];\n        foreach (int num in numbers)\n        {\n            if (num > max)\n                max = num;\n        }\n        return max;\n    }\n}\n",
                            Titre = "Trouver le maximum"
                        },
                        new
                        {
                            IDExercice = 6,
                            Enonce = "Développez une méthode IsPalindrome dans la classe Exercice qui prend un string comme entrée et retourne un bool indiquant si le string est un palindrome ou non (un palindrome se lit de la même manière dans les deux sens).",
                            IDDifficulte = 2,
                            IDLecon = 2,
                            IDStatut = 2,
                            Modele = "// code-insertion-point\n\npublic class Test \n{\n    public static TestResult Ensure(string input, bool expected) \n    {\n        TestStatus status = TestStatus.Passed;\n        bool actual = false;\n        try \n        {\n            actual = Exercice.IsPalindrome(input);\n            if(actual != expected) \n            {\n                status = TestStatus.Failed;\n            }\n        } \n        catch(Exception ex) \n        {\n            status = TestStatus.Inconclusive;\n        }\n\n        return new TestResult(\n            string.Format(\"'{0}' should be a palindrome: {1}\", input, expected),\n            status,\n            status == TestStatus.Passed ? string.Empty : string.Format(\"Expected {0}. Got {1}.\", expected, actual)\n        );  \n    }\n}\n\nreturn new TestResult[] {\n    Test.Ensure(\"racecar\", true),\n    Test.Ensure(\"hello\", false),\n    Test.Ensure(\"Anna\", true),\n    Test.Ensure(\"A man a plan a canal Panama\", true)\n};\n",
                            Position = 2,
                            Solution = "public class Exercice\n{\n    public static bool IsPalindrome(string input)\n    {\n        string cleanedInput = input.ToLower().Replace(\" \", \"\").Replace(\",\", \"\").Replace(\".\", \"\");\n        char[] charArray = cleanedInput.ToCharArray();\n        Array.Reverse(charArray);\n        string reversedString = new string(charArray);\n        return cleanedInput == reversedString;\n    }\n}\n",
                            Titre = "Est-ce un palindrome?"
                        });
                });

            modelBuilder.Entity("Puroguramu.Domains.Models.Group", b =>
                {
                    b.Property<int>("IDGroupe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDGroupe"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("IDGroupe");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            IDGroupe = 1,
                            Nom = "2i1"
                        },
                        new
                        {
                            IDGroupe = 2,
                            Nom = "2i2"
                        },
                        new
                        {
                            IDGroupe = 3,
                            Nom = "2i3"
                        },
                        new
                        {
                            IDGroupe = 4,
                            Nom = "2i4"
                        });
                });

            modelBuilder.Entity("Puroguramu.Domains.Models.Lesson", b =>
                {
                    b.Property<int>("IDLecon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDLecon"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDStatut")
                        .HasColumnType("int");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("IDLecon");

                    b.HasIndex("IDStatut");

                    b.HasIndex("Intitule")
                        .IsUnique();

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            IDLecon = 1,
                            Description = "Cette leçon couvre les bases de C#, incluant la syntaxe de base, les types de données et les méthodes simples.",
                            IDStatut = 2,
                            Intitule = "Introduction à C#",
                            Position = 1
                        },
                        new
                        {
                            IDLecon = 2,
                            Description = "Cette leçon explore les structures de contrôle en C#, telles que les boucles et les instructions conditionnelles.",
                            IDStatut = 2,
                            Intitule = "Structures de contrôle en C#",
                            Position = 2
                        },
                        new
                        {
                            IDLecon = 3,
                            Description = "Cette leçon couvre les concepts de base de la programmation orientée objet en C#.",
                            IDStatut = 2,
                            Intitule = "Programmation orientée objet en C#",
                            Position = 3
                        },
                        new
                        {
                            IDLecon = 4,
                            Description = "Cette leçon couvre la gestion des exceptions en C#.",
                            IDStatut = 2,
                            Intitule = "Gestion des exceptions en C#",
                            Position = 4
                        },
                        new
                        {
                            IDLecon = 5,
                            Description = "Cette leçon couvre la programmation asynchrone en C#.",
                            IDStatut = 2,
                            Intitule = "Programmation asynchrone en C#",
                            Position = 5
                        });
                });

            modelBuilder.Entity("Puroguramu.Domains.Models.ProgressStatus", b =>
                {
                    b.Property<int>("IDStatut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDStatut"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IDStatut");

                    b.ToTable("ProgressStatus");

                    b.HasData(
                        new
                        {
                            IDStatut = 1,
                            Nom = "À faire"
                        },
                        new
                        {
                            IDStatut = 2,
                            Nom = "En cours"
                        },
                        new
                        {
                            IDStatut = 3,
                            Nom = "Résolu"
                        },
                        new
                        {
                            IDStatut = 4,
                            Nom = "Abandonné"
                        });
                });

            modelBuilder.Entity("Puroguramu.Domains.Models.Statut", b =>
                {
                    b.Property<int>("IDStatut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDStatut"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IDStatut");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            IDStatut = 1,
                            Nom = "Masqué"
                        },
                        new
                        {
                            IDStatut = 2,
                            Nom = "Publié"
                        });
                });

            modelBuilder.Entity("Puroguramu.Infrastructures.DbContexts.Progress", b =>
                {
                    b.Property<int>("IDProgres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProgres"), 1L, 1);

                    b.Property<string>("CodeDerniereTentative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateDerniereTentative")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IDExercice")
                        .HasColumnType("int");

                    b.Property<int>("IDStatut")
                        .HasColumnType("int");

                    b.Property<string>("IDUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDProgres");

                    b.HasIndex("IDExercice");

                    b.HasIndex("IDStatut");

                    b.HasIndex("IDUtilisateur");

                    b.ToTable("Progress");
                });

            modelBuilder.Entity("Puroguramu.Infrastructures.DbContexts.PuroUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("GroupeIDGroupe")
                        .HasColumnType("int");

                    b.Property<int>("IDGroupe")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("GroupeIDGroupe");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Puroguramu.Infrastructures.DbContexts.PuroUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Puroguramu.Infrastructures.DbContexts.PuroUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Puroguramu.Infrastructures.DbContexts.PuroUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Puroguramu.Infrastructures.DbContexts.PuroUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Puroguramu.Domains.Models.Exercise", b =>
                {
                    b.HasOne("Puroguramu.Domains.Models.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("IDDifficulte")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Puroguramu.Domains.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("IDLecon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Puroguramu.Domains.Models.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("IDStatut")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Lesson");

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("Puroguramu.Domains.Models.Lesson", b =>
                {
                    b.HasOne("Puroguramu.Domains.Models.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("IDStatut")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("Puroguramu.Infrastructures.DbContexts.Progress", b =>
                {
                    b.HasOne("Puroguramu.Domains.Models.Exercise", "Exercice")
                        .WithMany()
                        .HasForeignKey("IDExercice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Puroguramu.Domains.Models.ProgressStatus", "ProgressStatus")
                        .WithMany()
                        .HasForeignKey("IDStatut")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Puroguramu.Infrastructures.DbContexts.PuroUser", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IDUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("ProgressStatus");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Puroguramu.Infrastructures.DbContexts.PuroUser", b =>
                {
                    b.HasOne("Puroguramu.Domains.Models.Group", "Groupe")
                        .WithMany()
                        .HasForeignKey("GroupeIDGroupe");

                    b.Navigation("Groupe");
                });
#pragma warning restore 612, 618
        }
    }
}
